### PR TITLE
Kubernetes deployment manifests

### PR DESCRIPTION
**Pull request by maeb**
This PR adds Dockerfiles for solr and solrwayback seeking to modularize the existing Dockerfile as the current one is not suitable to build deployment manifests around.

### CODE REVIEW

**Comment by trym-b** [comment]
We decided to leave this PR alone until we have documented properly what the "diff" between this setup and the `solrwayback` bundle is.

**Comment by maeb** [comment]
This PR now also adds kubernetes deployment manifests and a Dockerfile with the warc-indexer.

**Comment by maeb** [comment]
The deployment manifests will not be part of this repository and a new PR will be made against https://github.com/nlnwa/nettarkivet-deploy.

Only the Dockerfiles and CI should end up here.

**Comment by maeb** [comment]
As mentioned we are in a process of moving the deployment manifests to our internal deployment repository, so closing this PR on that basis.

**Pull request closed without merging**
