### PR TITLE
feat: ensure arguments in sync

### PR DESCRIPTION
**Pull request by trym-b**
# Motivation

Since commit 25360d97b367eff0c75a81ee456f446469892907 we have had to keep the sets of arguments in sync between the `Dockerfile`s and the `workflow` files. It is easy to forget to keep the arguments in sync, so instead this should be verified automatically.

# Implementation

The main idea is to populate a `dict` with the following structure:
```
{
    argumentA: {
        versionA: [PathA, PathB, ...]
        versionB: [PathB, PathC, ...]
        ...
    },
    argumentB: {
        versionX: [PathA, PathB, ...]
        versionY: [PathB, PathC, ...]
        ...
    },
    ...
}
```

After populating the `dict` we must ensure that every argument only have one version, otherwise we raise an exception.

# Testing

A simple `pytest` test is added to ensure we have basic testing. This test is also run in a workflow.

### CODE REVIEW

**Review by andrbo — APPROVED** [review]

**Review by maeb — COMMENTED** [review]
The problem with this check is that it could be done with a bash twoliner:

```shell
- name: Ensure arguments in sync
        run: |
          # comm -3 file1 file2 - leave out lines from both file1 and file2
          DIFF=$(comm -3 <(grep -hE "ARG.*(VERSION|TAG)=[0-9]" Dockerfile.* | sed 's/ARG//' | awk '{print $1}' | sort -u) <(grep -hE "(VERSION|TAG)=[0-9]" .github/workflows/*.yml | awk '{print $1}' | sort -u))
         [[ -z $DIFF ]] ||  exit 1
```

Even tough it is dense and not easy to parse at first glance, I argue that it is MUCH easier to parse than the python check.

**Comment by trym-b** [comment]
> The problem with this check is that it could be done with a bash twoliner:
> 
> ```shell
> - name: Ensure arguments in sync
>         run: |
>           # comm -3 file1 file2 - leave out lines from both file1 and file2
>           DIFF=$(comm -3 <(grep -hE "ARG.*(VERSION|TAG)=[0-9]" Dockerfile.* | sed 's/ARG//' | awk '{print $1}' | sort -u) <(grep -hE "(VERSION|TAG)=[0-9]" .github/workflows/*.yml | awk '{print $1}' | sort -u))
>          [[ -z $DIFF ]] ||  exit 1
> ```
> 
> Even tough it is dense and not easy to parse at first glance, I argue that it is MUCH easier to parse than the python check.

As I see it we have two alternative approaches, I'll call them `Approach A` and `Approach B`

`Approach A`, where we add a bash one/two liner and call it a day. The goal is to get code out the door as fast as possible.

In my opinion, this approach has the following qualities:

1. It can be fast to roll out
2. It is difficult to test, which makes it unclear if the code actually works
3. Brittle during refactoring, how do you know you did not break it? (related to 2)

`Approach B`, where we add tests to ensure the code does not break before we deploy or during later refactoring/changes.

As I see it, this approach has the following qualities:

1. It can potentially be more time-intensive
2. Tests included, no need to worry about whether the code works or not
3. Easier to refactor/change, as you can rely on the tests to avoid regressions

Of course, it is not so that one approach is better than the other in all situations. This may lead us to why we disagree on this point, which I think is the `life cycle` of this repository.

If we know for a fact that this repo will only be in use for a limited time, then yes maybe `Approach A` might be better suited. However, my hunch is that we will use this repo for a much longer timeframe than we might guess, which is why I want proper tests.

**Comment by maeb** [comment]
Because I already disagreed with the necessity of this check I also disagree to introduce this much code to do the check.

Also I disagree the Approach A in this particular case is:

1. difficult to test (point 2). It is very easy to run the test locally and very easy to run each step separately.
2. brittle during refactoring (point 3). The brittleness depends on the specific implementation and in my example it is just as brittle as the python code if we replace the regex given to grep with the regex given in the python code.

**Review by maeb — APPROVED** [review]

**Comment by trym-b** [comment]
After an IRL discussion, we decided to merge this anyway. Next time we will ensure we are talking about the same approach before we start coding.

**Pull request merged**
